# Site settings
title: Shiyanping's Blog
SEOTitle: 燕平的博客·Fighting
header-img: img/home-bg-o.jpg
email: 594388036@qq.com
description: "石燕平的个人博客，用于记录学习笔记，写一些日常所学文章和生活纪实，内容大概包括前端，Node，游记，个人感想等。"
keyword: "石燕平, shiyanping, Shiyanping's, 石燕平的博客, 燕平的博客, 燕平的博客·Fighting, Shiyanping's Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端"
url: "https://Shiyanping.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
juejin_username: 59c27af36fb9a00a5831832e
github_username: Shiyanping
resume_url: https://www.shiyanping.top/resume



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "业精于勤荒于嬉，行成于思毁于随"
sidebar-avatar: /img/avatar-xs.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
# friends: [
    # {
    #     title: "小冲的博客",
    #     href: "http://blog.ctomorrow.top/"
    # }
# ]

# Friends
collection: [
    {
        title: "阮一峰的博客",
        href: "http://www.ruanyifeng.com/blog/"
    },
    {
        title: "张鑫旭的博客",
        href: "https://www.zhangxinxu.com/"
    }
]
